version: '3'
services:

    #PHP
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: habib/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network

    #Nginx
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8989:8989"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL
    db_flow:
        container_name: db_flow
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: flow
            MYSQL_USER: flow
            MYSQL_PASSWORD: flow
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - app-network

#Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
